#### crowsnest.conf
#### This is the default config after installation.
#### It is also used as the default config in MainsailOS.
#### For details on how to configure this to your needs, see:
#### https://github.com/mainsail-crew/crowsnest/blob/master/README.md


#####################################################################
####                                                            #####
####      Information about ports and according URL's           #####
####                                                            #####
#####################################################################
####                                                            #####
####    Port 8080 equals /webcam/?action=[stream/snapshot]      #####
####    Port 8081 equals /webcam2/?action=[stream/snapshot]     #####
####    Port 8082 equals /webcam3/?action=[stream/snapshot]     #####
####    Port 8083 equals /webcam4/?action=[stream/snapshot]     #####
####                                                            #####
####    Note: These ports are default for most Mainsail         #####
####    installations. Using any other port would involve       #####
####    changing the proxy configuration or using URLs          #####
####    with the specific port like                             #####
####    http://<ip>:<port>/?action=[stream/snapshot]            #####
####                                                            #####
#####################################################################
####    RTSP Stream URL: ( if enabled and supported )           #####
####    rtsp://<ip>:<rtsp_port>/stream.h264                     #####
#####################################################################


[crowsnest]
log_path: /home/pi/printer_data/logs/crowsnest.log
log_level: verbose
delete_log: true       # Set to true temporarily to clear old errors

[cam 1]
mode: ustreamer
port: 8080
device: /dev/v4l/by-id/usb-PC-LM1E_PC-LM1E_PC-LM1E-video-index0
resolution: 640x480       # Drop to 480p temporarily to test if lag vanishes
max_fps: 10               # Lower FPS to 10
#custom_flags: --format=MJPG

[cam 2]
mode: ustreamer
port: 8081
device: /dev/v4l/by-id/usb-Vimicro_corp._PC-LM1E_Camera_PC-LM1E_Audio-video-index0
resolution: 640x480
max_fps: 10
#custom_flags: --format=MJPG
